#  Numpy
Python NumPy is the core library for scientific computing in Python. NumPy provides a high-performance
multidimensional array object and tools for working with these arrays.

#### PYTHON NUMPY ARRAY

In [1]:
import numpy

In [2]:
a = numpy.array([3, 2, 3])
print('print rank 1 array:')

print rank 1 array:


In [3]:
# access the array using their index
print('print using their index: a[0]= ', a[0])

print using their index: a[0]=  3


In [4]:
a[0] = 5 # modify the array
print('print using slicing : ', a[1:]) # slicing can be used also

print using slicing :  [2 3]


In [5]:
# print the whole list
print('Print the whole array : ', a)


Print the whole array :  [5 2 3]


In [6]:
# Create a rank 2 array using nested Python list
b = numpy.array([[10, 20, 30], [40, 50, 60]])
print('\nprint rank 2 array')


print rank 2 array


In [7]:
# access them using their index
print('print using their index: b[0,0]= ', b[0, 0], ' b[0,1]= ',b[0, 1])
print('print using slicing ', b[1:, :2]) # 1st slice for row, 2nd for column

print using their index: b[0,0]=  10  b[0,1]=  20
print using slicing  [[40 50]]


In [8]:
# initialize a zero matrix
a = numpy.zeros((2, 2))
print('\nprint a 2-by-2 zero matrix:\n', a)


print a 2-by-2 zero matrix:
 [[ 0.  0.]
 [ 0.  0.]]


In [9]:
# Create an array of all ones
b = numpy.ones((2, 2))
print('\nprint a 2-by-2 all one matrix:\n', b)


print a 2-by-2 all one matrix:
 [[ 1.  1.]
 [ 1.  1.]]


In [10]:
# Create a constant array
c = numpy.full((3, 3), 6)
print('\nprint a 3-by-3 constant matrix for value = 6:\n', c)


print a 3-by-3 constant matrix for value = 6:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [11]:
# Create a 3x3 identity matrix
d = numpy.eye(3)
print('\nprint a 3-by-3 identity matrix:\n', d)


print a 3-by-3 identity matrix:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### PYTHON NUMPY TUTORIAL – ARITHMETIC OPERATION ON MATRIX


In [12]:
import numpy

In [13]:
# initialize two array
x = numpy.array([[1, 2], [3, 4]], dtype=numpy.float64)
y = numpy.array([[3, 4], [5, 6]], dtype=numpy.float64)


In [14]:
print('Print the two matrices')
print('X = \n', x)
print('Y = \n', y)


Print the two matrices
X = 
 [[ 1.  2.]
 [ 3.  4.]]
Y = 
 [[ 3.  4.]
 [ 5.  6.]]


In [15]:
# Elementwise sum; both produce the array
print('\nElementwise addition of two matrices: ( X + Y of Matlab )')
print('Add using add operator: \n', x + y)
print('Add using add function: \n', numpy.add(x, y))


Elementwise addition of two matrices: ( X + Y of Matlab )
Add using add operator: 
 [[  4.   6.]
 [  8.  10.]]
Add using add function: 
 [[  4.   6.]
 [  8.  10.]]


In [16]:
# Elementwise difference; both produce the array
print('\nElementwise subtraction of two matrices: ( X - Y of Matlab )')
print('Subtract using operator: \n', x - y)
print('Subtract using function: \n', numpy.subtract(x, y))


Elementwise subtraction of two matrices: ( X - Y of Matlab )
Subtract using operator: 
 [[-2. -2.]
 [-2. -2.]]
Subtract using function: 
 [[-2. -2.]
 [-2. -2.]]


In [17]:
# Elementwise product; both produce the array
print('\nElementwise Multiplication of two matrices: ( X .* Y of Matlab )')
print('Multiply using operator: \n', x * y)
print('Multiply using function: \n', numpy.multiply(x, y))


Elementwise Multiplication of two matrices: ( X .* Y of Matlab )
Multiply using operator: 
 [[  3.   8.]
 [ 15.  24.]]
Multiply using function: 
 [[  3.   8.]
 [ 15.  24.]]


In [18]:
# Elementwise division; both produce the array
print('\nElementwise division of two matrices: ( X ./ Y of Matlab )')
print('Division using operator: \n', x / y)
print('Division using function: \n', numpy.divide(x, y))


Elementwise division of two matrices: ( X ./ Y of Matlab )
Division using operator: 
 [[ 0.33333333  0.5       ]
 [ 0.6         0.66666667]]
Division using function: 
 [[ 0.33333333  0.5       ]
 [ 0.6         0.66666667]]


In [19]:
# Elementwise square root; produces the array
print('\nSquare root each element of X matrix\n', numpy.sqrt(x))
# Matrix Multiplication
print('\nMatrix Multiplication of two matrices: ( X * Y of Matlab )')
print(x.dot(y))


Square root each element of X matrix
 [[ 1.          1.41421356]
 [ 1.73205081  2.        ]]

Matrix Multiplication of two matrices: ( X * Y of Matlab )
[[ 13.  16.]
 [ 29.  36.]]
